ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/TR_Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_My_Test_Execution_as_Tester__c.field-meta.xml
<CustomField>
    <fullName>TR_My_Test_Execution_as_Tester__c</fullName>
    <description>To create Salesforce record list view (My Test Execution) where Tester = Logged In User.</description>
    <formula>IF( TR_Tester__r.Id  =  $User.Id , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>My Test Execution as Tester</label>
    <type>Checkbox</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Started</fullName>
                <color>#78C953</color>
                <label>Started</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <color>#0B6FCE</color>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Awaiting Retest</fullName>
                <color>#A845DC</color>
                <label>Awaiting Retest</label>
            </value>
            <value>
                <fullName>Parked</fullName>
                <color>#F3D904</color>
                <label>Parked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Test_Outcome__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Outcome__c</fullName>
    <label>Test Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
                <color>#0B6FCE</color>
                <label>Passed</label>
            </value>
            <value>
                <fullName>Passed with minor issues</fullName>
                <color>#F3D904</color>
                <label>Passed with minor issues</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <color>#FF0000</color>
                <label>Failed</label>
            </value>
            <value>
                <fullName>Not Executed</fullName>
                <color>#A845DC</color>
                <default>true</default>
                <label>Not Executed</label>
            </value>
            <value>
                <fullName>Blocked for Testing</fullName>
                <isActive>false</isActive>
                <label>Blocked for Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/TR_Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_My_Tickets_as_Tester__c.field-meta.xml
<CustomField>
    <fullName>TR_My_Tickets_as_Tester__c</fullName>
    <description>To create Salesforce record list view (My Ticket) where Tester = Logged In User</description>
    <formula>IF( TR_Tester__r.TR_User__r.Id  = $User.Id , TRUE, FALSE )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>My Tickets as Tester</label>
    <type>Checkbox</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raised</fullName>
                <default>true</default>
                <label>Raised</label>
            </value>
            <value>
                <fullName>In Analysis</fullName>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Ready for Deployment</fullName>
            </value>
            <value>
                <fullName>Ready for Testing</fullName>
            </value>
            <value>
                <fullName>Closed - Complete</fullName>
            </value>
            <value>
                <fullName>Closed - Cannot Replicate</fullName>
            </value>
            <value>
                <fullName>Closed - Consolidated</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
                <isActive>false</isActive>
                <label>Escalated</label>
            </value>
            <value>
                <fullName>In Test</fullName>
                <isActive>false</isActive>
                <label>In Test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Execution</label>
    <referenceTo>TR_Test_Execution__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/classes/TR_TaskCounterClass.cls
public with sharing class TR_TaskCounterClass {

    @AuraEnabled(cacheable=true)
    public static integer getTestExecutionRecord(String userId){
    return [SELECT COUNT() FROM TR_Test_Execution__c WHERE TR_Test_Outcome__c = 'Not Executed' AND TR_My_Test_Execution_as_Tester__c = TRUE ];
    }    

    @AuraEnabled(cacheable=true)
    public static integer getMyOwnTickets( String userId){
        return [SELECT COUNT() FROM TR_Ticket__c WHERE TR_Status__c = 'Ready for Testing' AND TR_My_Tickets_as_Tester__c = TRUE];
    }
}