ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/TR_Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Deadline__c.field-meta.xml
<CustomField>
    <fullName>TR_Deadline__c</fullName>
    <description>Deadline to complete the test execution</description>
    <label>Deadline</label>
    <type>Date</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Ext_Execute_Now__c.field-meta.xml
<CustomField>
    <fullName>TR_Ext_Execute_Now__c</fullName>
    <description>Execute Now (for Experience Cloud only)</description>
    <formula>$Label.TR_exp_cloud_base_url&amp;&quot;/protrack/s/test-execute-outcome?c__recordId=&quot;&amp;Id</formula>
    <label>Execute Now</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_My_Test_Execution_as_Tester__c.field-meta.xml
<CustomField>
    <fullName>TR_My_Test_Execution_as_Tester__c</fullName>
    <description>To create Salesforce record list view (My Test Execution) where Tester = Logged In User.</description>
    <formula>IF( TR_Tester__r.Id  =  $User.Id , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>My Test Execution as Tester</label>
    <type>Checkbox</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Started</fullName>
                <color>#78C953</color>
                <label>Started</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <color>#0B6FCE</color>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Awaiting Retest</fullName>
                <color>#A845DC</color>
                <label>Awaiting Retest</label>
            </value>
            <value>
                <fullName>Parked</fullName>
                <color>#F3D904</color>
                <label>Parked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Test_Outcome__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Outcome__c</fullName>
    <label>Test Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
                <color>#0B6FCE</color>
                <label>Passed</label>
            </value>
            <value>
                <fullName>Passed with minor issues</fullName>
                <color>#F3D904</color>
                <label>Passed with minor issues</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <color>#FF0000</color>
                <label>Failed</label>
            </value>
            <value>
                <fullName>Not Executed</fullName>
                <color>#A845DC</color>
                <default>true</default>
                <label>Not Executed</label>
            </value>
            <value>
                <fullName>Blocked for Testing</fullName>
                <isActive>false</isActive>
                <label>Blocked for Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Test_Title__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Title__c</fullName>
    <formula>TR_Template__r.TR_Test_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Test Title</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/classes/TR_TestExecutionController.cls
public with sharing class TR_TestExecutionController {
    public TR_TestExecutionController() {

    }
    @AuraEnabled(cacheable=true)
    public static List<TR_Test_Execution__c> getTestExecutions(Integer offSetCount){
        return [
            SELECT Name, 
            TR_Test_Title__c, 
            TR_Deadline__c, 
            TR_Status__c, 
            TR_Ext_Execute_Now__c from TR_Test_Execution__c
            WHERE TR_My_Test_Execution_as_Tester__c = TRUE
            AND TR_Test_Outcome__c = 'Not Executed'
            ORDER BY TR_Deadline__c, Name
            LIMIT 50 OFFSET :offSetCount
        ];
    }
}