ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/TR_Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Template__c.field-meta.xml
<CustomField>
    <fullName>TR_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Tester__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/TR_Test_Execution_Step__c.object-meta.xml
<CustomObject>
    <label>Test Execution Step</label>
    <nameField>
        <displayFormat>TES-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Action__c.field-meta.xml
<CustomField>
    <fullName>TR_Action__c</fullName>
    <label>Action</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Comments__c.field-meta.xml
<CustomField>
    <fullName>TR_Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Sequence__c.field-meta.xml
<CustomField>
    <fullName>TR_Sequence__c</fullName>
    <formula>IF(LEN(TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c)) &lt;2, &quot;0&quot; &amp; TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c ), TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sequence</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Step_Outcome__c.field-meta.xml
<CustomField>
    <fullName>TR_Step_Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
                <color>#0B6FCE</color>
                <label>Pass</label>
            </value>
            <value>
                <fullName>Passed with issues</fullName>
                <color>#F3D904</color>
                <label>Passed with issues</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <color>#FF0000</color>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Execution__c</fullName>
    <label>Test Execution</label>
    <referenceTo>TR_Test_Execution__c</referenceTo>
    <relationshipLabel>Test Execution Steps</relationshipLabel>
    <relationshipName>Test_Execution_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Tester_Role__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester_Role__c</fullName>
    <label>Tester Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Tips__c.field-meta.xml
<CustomField>
    <fullName>TR_Tips__c</fullName>
    <label>Tips</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/TR_Test_Script__c.object-meta.xml
<CustomObject>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Tester_Role__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester_Role__c</fullName>
    <label>Tester Role</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Tester__c/TR_Tester__c.object-meta.xml
<CustomObject>
    <label>Tester</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tester Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Testers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Tester__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Tester__c/fields/TR_Test_Template__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Template</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Test Script Testers</relationshipLabel>
    <relationshipName>Testers</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Tester__c/fields/TR_User__c.field-meta.xml
<CustomField>
    <fullName>TR_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Testers</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/TR_Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>TR_Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Execution</label>
    <referenceTo>TR_Test_Execution__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Script__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Tester__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tester</label>
    <referenceTo>TR_Tester__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Tickets (User Story)</relationshipLabel>
    <relationshipName>Tickets1</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/TR_User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Allocated_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Allocated_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Once it has been agreed with the client which sprint will be accommodated for this User Story, use this field to keep this information</inlineHelpText>
    <label>Allocated Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Allocated User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/globalValueSets/TR_Test_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sprint Testing</fullName>
    </customValue>
    <customValue>
        <fullName>SIT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>UAT</fullName>
    </customValue>
    <masterLabel>Test Phase</masterLabel>
</GlobalValueSet>

ProTrackDev/force-app/main/default/classes/TR_RunTestScript_Controller.cls
public class TR_RunTestScript_Controller {

    private final TR_Test_Execution__c texec;
    public List<TR_Test_Execution_Step__c> TestSp{get;set;}
    public List<TR_Ticket__c> bugs{get;set;}
    public boolean isnewBugs{get;set;}
    public string testId{get;set;}
    public string testName{get;set;}
    public boolean stepsComplete{get;set;}
    private Id projectId;
    public TR_Test_Script__c template{get;set;}
    private static final string defaultTicketStat = 'Raised';
    private list<String> texecFields; 
    private Id testUserId;
    public string testerRole {get;set;}
    
    public TR_RunTestScript_Controller(ApexPages.StandardController stdController) {
        stdController.addFields(new list<String>{'TR_Template__c','TR_Test_Phase__c','TR_Tester__c','Id'});
        this.texec = (TR_Test_Execution__c)stdController.getRecord();
        projectId = [SELECT TR_Project__c FROM TR_Test_Execution__c WHERE Id =: this.texec.Id].TR_Project__c;
        TestSp = [SELECT TR_Sequence__c,Name,TR_Action__c,TR_Expected_Result__c,TR_Step_Outcome__c,TR_Comments__c,TR_Tips__c,Id,
                         TR_Tester_Role__c
                  FROM TR_Test_Execution_Step__c WHERE TR_Test_Execution__c =: this.texec.Id
                  ORDER BY TR_Sequence__c ASC];
        if(TestSP.isEmpty() || TestSp == null){ TestSp = new List<TR_Test_Execution_Step__c>();}
        bugs = new List<TR_Ticket__c>();
        template = [SELECT Id,TR_User_Story__r.Id,TR_User_Story__r.TR_Allocated_Sprint__c,TR_Tester_Role__c
                    FROM TR_Test_Script__c WHERE Id =: this.texec.TR_Template__c];
        testUserId = [SELECT Id FROM TR_Tester__c
                      WHERE TR_User__c =: this.texec.TR_Tester__c
                      AND TR_Test_Template__c =: this.texec.TR_Template__c
                      LIMIT 1].Id;
        isnewBugs = false;
        testId = '';
        testName = '';
        stepsComplete = false;
    }
    
    public void addBug(){
        isnewBugs = true;
        bugs.add(new TR_Ticket__c());
        testId =  System.currentPageReference().getParameters().get('testId');
        if(bugs.size() > 0){
            for(integer i = 0; i< bugs.size(); i++){
                bugs[i].TR_Project__c = projectId;
                bugs[i].TR_User_Story__c = template.TR_User_Story__r.Id;
                bugs[i].TR_Sprint__c = template.TR_User_Story__r.TR_Allocated_Sprint__c;
                bugs[i].TR_Status__c = defaultTicketStat;
                bugs[i].TR_Tester__c = testUserId;
                bugs[i].TR_Log_Time__c = system.now();
                bugs[i].TR_Logged_by__c = system.userInfo.getUserId();
                bugs[i].TR_Test_Phase__c = this.texec.TR_Test_Phase__c;
                bugs[i].TR_Test_Script__c = this.texec.TR_Template__c;
            }
        }
    }
    
    public PageReference AttachFile() {
        if(TestSp.size() > 0){
            update TestSp;
        }
        testId =  System.currentPageReference().getParameters().get('testId');
        testName =  System.currentPageReference().getParameters().get('testName');
        PageReference redirect = new PageReference('/p/attach/NoteAttach?parentname='+testName+'&pid='+testId
                                                    +'&retURL='+'/apex/TR_RunTestScript?Id='+texec.Id); 
        redirect.setRedirect(true); 
    
        return redirect;
    }
    
    public PageReference  save(){
        try{
            insert bugs;

            if(TestSp.size() > 0){
                update TestSp;
            }
            
            update texec;
        }catch(Exception ex){
            
        }
        
        if(!string.isBlank(texec.TR_Overall_Test_Comments__c) && !string.isBlank(texec.TR_Test_Outcome__c)){
            PageReference backToPrevious = new PageReference('/'+texec.Id);
            backToPrevious.setRedirect(true); 
            return backToPrevious;  
        }else{
            stepsComplete = true;
            ApexPages.addMessage(
            new ApexPages.message(ApexPages.Severity.FATAL,system.label.TR_Test_Execution_Message_01));
            return null;
        }
    }

}