ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/TR_Test_Script__c.object-meta.xml
<CustomObject>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/TR_Test_Script_Step__c.object-meta.xml
<CustomObject>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Action__c.field-meta.xml
<CustomField>
    <fullName>TR_Action__c</fullName>
    <label>Action</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Action_Long__c.field-meta.xml
<CustomField>
    <fullName>TR_Action_Long__c</fullName>
    <label>Action Long</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Ranked_Sequence__c.field-meta.xml
<CustomField>
    <fullName>TR_Ranked_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Sequence_Last_Updated_By__c.field-meta.xml
<CustomField>
    <fullName>TR_Sequence_Last_Updated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sequence Last Updated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Script_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Test_Script__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Script</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Test Script Steps</relationshipLabel>
    <relationshipName>Test_Script_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/classes/TR_SequenceTestSteps_Controller.cls
public  with sharing class TR_SequenceTestSteps_Controller  {
    public List<TR_Test_Script_Step__c> TestSteps {get;set;}
    public Id scriptID {get;set;}
    public string sortedIDs{get;set;}
    public string UpdatedTSId {get;set;}
    public List<TR_Test_Script_Step__c> Steps {get;set;}
    public static List<TR_Test_Script_Step__c> StepOrder {get;set;}
    
    public TR_SequenceTestSteps_Controller(){
        scriptID = ApexPages.currentPage().getParameters().get('TKR_Test_Templates'); 
        if(scriptID != null){
            TestSteps = [SELECT TR_Action__c, TR_Action_Long__c,
                                TR_Expected_Result__c, TR_Ranked_Sequence__c,
                                TR_Sequence_Last_Updated_By__r.Name, TR_Test_Script__c,
                                Id,Name
                         FROM TR_Test_Script_Step__c WHERE TR_Test_Script__c =: scriptID
                         ORDER BY TR_Ranked_Sequence__c ASC];
        }
    }
    
    @RemoteAction
    public static List<TR_Test_Script_Step__c> updateSortOrder(List<String> sortedIDs, String UpdatedTSId) {
        Set<String> stepsId = new Set<String>();
        Map<String, Integer> seqOrderMap = new Map<String, Integer>();
        for(String ids : sortedIDs){
            stepsId.add(ids.left(18));
        }
        StepOrder = [SELECT TR_Action__c, TR_Action_Long__c,
                    TR_Expected_Result__c, TR_Ranked_Sequence__c,
                    TR_Sequence_Last_Updated_By__c,
                    TR_Sequence_Last_Updated_By__r.Name, TR_Test_Script__c,
                    Id,Name
                    FROM TR_Test_Script_Step__c WHERE Id IN: stepsId];
        
        Integer index;            
        for(Integer i = 0; i < sortedIDs.size(); i++){
            index = i+1;
            seqOrderMap.put(sortedIDs[i].left(18), index);    
        } 
        
        for(TR_Test_Script_Step__c rec : StepOrder){
            if(seqOrderMap.containsKey(rec.Id)){
                rec.TR_Ranked_Sequence__c = Decimal.valueOf(seqOrderMap.get(rec.Id));
                rec.TR_Sequence_Last_Updated_By__c = userinfo.getuserid();
            }
        }
        update StepOrder;

        return StepOrder;
                
    }
}