ProTrackDev/force-app/main/default/objects/TR_Design_User_Story_Association__c/TR_Design_User_Story_Association__c.object-meta.xml
<CustomObject>
    <description>Junction object to relate User Stories and Tech Design</description>
    <label>Design - User Story Association</label>
    <nameField>
        <displayFormat>TD-US{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Design User Story Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Design_User_Story_Association__c/fields/TR_Technical_Design__c.field-meta.xml
<CustomField>
    <fullName>TR_Technical_Design__c</fullName>
    <inlineHelpText>Associated design</inlineHelpText>
    <label>Technical Design</label>
    <referenceTo>TR_Technical_Design__c</referenceTo>
    <relationshipLabel>Related User Story</relationshipLabel>
    <relationshipName>Design_User_Story_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Design_User_Story_Association__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <inlineHelpText>Associated user story</inlineHelpText>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Related Technical Design</relationshipLabel>
    <relationshipName>Design_User_Story_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Project__c/TR_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Release__c/TR_Release__c.object-meta.xml
<CustomObject>
    <description>This object represents a release or phase for a specific project</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Release__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/TR_Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/fields/TR_Release__c.field-meta.xml
<CustomField>
    <fullName>TR_Release__c</fullName>
    <description>Release that is related to the sprint</description>
    <label>Release</label>
    <referenceTo>TR_Release__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/TR_Technical_Design__c.object-meta.xml
<CustomObject>
    <label>Technical Design</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Design Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technical Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Apex_Classes__c.field-meta.xml
<CustomField>
    <fullName>TR_Apex_Classes__c</fullName>
    <inlineHelpText>A list of apex classes (incuding test classes) used by this design</inlineHelpText>
    <label>Apex Classes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Apex_Trigger__c.field-meta.xml
<CustomField>
    <fullName>TR_Apex_Trigger__c</fullName>
    <inlineHelpText>A list of APEX triggers used by this design</inlineHelpText>
    <label>Apex Trigger</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Aura_Component__c.field-meta.xml
<CustomField>
    <fullName>TR_Aura_Component__c</fullName>
    <label>Aura Component</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Complexity__c.field-meta.xml
<CustomField>
    <fullName>TR_Complexity__c</fullName>
    <inlineHelpText>This will determine the amount of risk and amount of detailed design required</inlineHelpText>
    <label>Complexity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Data_Model__c.field-meta.xml
<CustomField>
    <fullName>TR_Data_Model__c</fullName>
    <inlineHelpText>Diagram or description of the Data Model relationships (ERD)</inlineHelpText>
    <label>Data Model</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Design_Name__c.field-meta.xml
<CustomField>
    <fullName>TR_Design_Name__c</fullName>
    <label>Design Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Design_Type__c.field-meta.xml
<CustomField>
    <fullName>TR_Design_Type__c</fullName>
    <label>Design Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SObject</fullName>
            </value>
            <value>
                <fullName>Setting</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Profile/Permission</fullName>
            </value>
            <value>
                <fullName>Customization</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Fields__c.field-meta.xml
<CustomField>
    <fullName>TR_Fields__c</fullName>
    <inlineHelpText>A list of fields (by Object, Record Type) used by this design</inlineHelpText>
    <label>Fields</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Flows__c.field-meta.xml
<CustomField>
    <fullName>TR_Flows__c</fullName>
    <label>Flows</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Lightning_Page__c.field-meta.xml
<CustomField>
    <fullName>TR_Lightning_Page__c</fullName>
    <description>List here any lightning page created or updated in this design</description>
    <inlineHelpText>List here any lightning page created or updated in this design</inlineHelpText>
    <label>Lightning Page (Flexi Page)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Lightning_Web_Component__c.field-meta.xml
<CustomField>
    <fullName>TR_Lightning_Web_Component__c</fullName>
    <label>Lightning Web Component</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Objects__c.field-meta.xml
<CustomField>
    <fullName>TR_Objects__c</fullName>
    <inlineHelpText>A list of Objects used by this design</inlineHelpText>
    <label>Objects</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Other_Components__c.field-meta.xml
<CustomField>
    <fullName>TR_Other_Components__c</fullName>
    <inlineHelpText>A list of other components related to this design (e.g. Email Templates, SAP scripts etc)</inlineHelpText>
    <label>Other Components</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Overview__c.field-meta.xml
<CustomField>
    <fullName>TR_Overview__c</fullName>
    <inlineHelpText>Descriptive overview of the design (e.g. how is it intended to work or be used?), including any process steps or key dependencies</inlineHelpText>
    <label>Overview</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Page_Layouts__c.field-meta.xml
<CustomField>
    <fullName>TR_Page_Layouts__c</fullName>
    <inlineHelpText>A list of page layouts used by this design.
Should include details if to be assigned to specific Record Types</inlineHelpText>
    <label>Page Layouts</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Technical Designs</relationshipLabel>
    <relationshipName>Technical_Designs</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_User_Interface_UI__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Interface_UI__c</fullName>
    <inlineHelpText>User Interface components and considerations
For example; Lightning components and associated configuration/customisation details</inlineHelpText>
    <label>User Interface (UI)/Lightning</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Technical_Design__c/fields/TR_Visualforce_Pages__c.field-meta.xml
<CustomField>
    <fullName>TR_Visualforce_Pages__c</fullName>
    <inlineHelpText>A list of Visualforce pages used by this design</inlineHelpText>
    <label>Visualforce Pages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/TR_User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Allocated_Release__c.field-meta.xml
<CustomField>
    <fullName>TR_Allocated_Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is automatically populated when you fill in the allocated Sprint</inlineHelpText>
    <label>Allocated Release</label>
    <referenceTo>TR_Release__c</referenceTo>
    <relationshipLabel>Allocated User Stories</relationshipLabel>
    <relationshipName>Allocated_User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Allocated_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Allocated_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Once it has been agreed with the client which sprint will be accommodated for this User Story, use this field to keep this information</inlineHelpText>
    <label>Allocated Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Allocated User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Epic_Name__c.field-meta.xml
<CustomField>
    <fullName>TR_Epic_Name__c</fullName>
    <formula>TR_Epic_Ref__r.TR_Epic_Name__c</formula>
    <label>Epic Name</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/classes/GeneratePdfTechnicalController.cls
public class GeneratePdfTechnicalController {
  public List<TR_Technical_Design__c> techDesignList { get; set; }
  List<TR_Technical_Design__c> allTechDesignList { get; set; }
  public List<GeneratePdfFunctionalController.EpicStoryWrapper> epicStoryWrapperList {
    get;
    set;
  }

  public GeneratePdfTechnicalController(
    ApexPages.StandardController stdController
  ) {
    TR_Release__c releaseRecord = (TR_Release__c) stdController.getRecord();
    Set<Id> userStoriesIds = new Set<Id>();
    List<TR_User_Story__c> userStoriesList = [
      SELECT
        Id,
        Name,
        TR_Allocated_Sprint__r.Name,
        TR_Epic_Name__c,
        TR_Allocated_Release__r.Name
      FROM TR_User_Story__c
      WHERE TR_Allocated_Release__c = :releaseRecord.Id
    ];
    Map<String, List<TR_User_Story__c>> epicStoryMap = new Map<String, List<TR_User_Story__c>>();
    //find all user stories'
    for (TR_User_Story__c userStory : userStoriesList) {
      userStoriesIds.add(userStory.Id);
      List<TR_User_Story__c> tmpMap = new List<TR_User_Story__c>();
      if (epicStoryMap.containsKey(userStory.TR_Epic_Name__c)) {
        tmpMap = epicStoryMap.get(userStory.TR_Epic_Name__c);
      }
      tmpMap.add(userStory);
      epicStoryMap.put(userStory.TR_Epic_Name__c, tmpMap);
    }

    epicStoryWrapperList = new List<GeneratePdfFunctionalController.EpicStoryWrapper>();
    for (String epicName : epicStoryMap.keySet()) {
      epicStoryWrapperList.add(
        new GeneratePdfFunctionalController.EpicStoryWrapper(
          epicName,
          epicStoryMap.get(epicName)
        )
      );
    }
    Set<Id> techDesignIdSet = new Set<Id>();
    System.debug('31-->' + userStoriesIds);
    for (TR_Design_User_Story_Association__c designUser : [
      SELECT Id, TR_Technical_Design__c
      FROM TR_Design_User_Story_Association__c
      WHERE TR_User_Story__c IN :userStoriesIds
    ]) {
      techDesignIdSet.add(designUser.TR_Technical_Design__c);
    }
    techDesignList = [
      SELECT
        id,
        Name,
        TR_Design_Name__c,
        OwnerId,
        TR_Design_Type__c,
        TR_Complexity__c,
        TR_Overview__c,
        TR_Data_Model__c,
        TR_User_Interface_UI__c,
        TR_Objects__c,
        TR_Fields__c,
        TR_Apex_Classes__c,
        TR_Apex_Trigger__c,
        TR_Other_Components__c,
        TR_Page_Layouts__c,
        TR_Visualforce_Pages__c,
        TR_Aura_Component__c,
        TR_Lightning_Web_Component__c,
        TR_Lightning_Page__c,
        TR_Flows__c,
        (
          SELECT
            id,
            name,
            TR_User_Story__r.Name,
            TR_User_Story__r.TR_Project__r.Name,
            TR_User_Story__r.TR_Allocated_Release__r.Name
          FROM Design_User_Story_Associations__r
        )
      FROM TR_Technical_Design__c
      WHERE id IN :techDesignIdSet
      ORDER BY CreatedDate DESC
    ];
    //SELECT  id,Name, TR_Project__r.Name, TR_Design_Name__c, TR_Lightning_Web_Component__c, (select id,name,TR_User_Story__r.Name from Design_User_Story_Associations__r) FROM TR_Technical_Design__c
  }
}