ProTrackDev/force-app/main/default/objects/TR_Sprint__c/TR_Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/fields/TR_End_Date__c.field-meta.xml
<CustomField>
    <fullName>TR_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/fields/TR_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>TR_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Planning</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/fields/TR_Total_Capacity_US_Points__c.field-meta.xml
<CustomField>
    <fullName>TR_Total_Capacity_US_Points__c</fullName>
    <description>Total Capacity for this sprint (in US points)</description>
    <label>Total Capacity (US Points)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/TR_User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Allocated_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Allocated_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Once it has been agreed with the client which sprint will be accommodated for this User Story, use this field to keep this information</inlineHelpText>
    <label>Allocated Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Allocated User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>TR_Completed_Date__c</fullName>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <label>0-Backlog</label>
            </value>
            <value>
                <fullName>Story Definition</fullName>
                <label>1-Story Definition</label>
            </value>
            <value>
                <fullName>Ready for Design</fullName>
                <label>2-Ready for Design</label>
            </value>
            <value>
                <fullName>In Design</fullName>
                <label>3-In Design</label>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
                <label>4-Ready for Development</label>
            </value>
            <value>
                <fullName>In Development</fullName>
                <label>5-In Development</label>
            </value>
            <value>
                <fullName>Ready for Sprint Demo</fullName>
                <label>6-Ready for Sprint Demo</label>
            </value>
            <value>
                <fullName>Ready for Deployment</fullName>
                <label>7-Ready for Deployment</label>
            </value>
            <value>
                <fullName>In Sprint Testing</fullName>
                <label>8-In Sprint Testing</label>
            </value>
            <value>
                <fullName>DONE</fullName>
                <label>9-DONE</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>99-Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Story_Point__c.field-meta.xml
<CustomField>
    <fullName>TR_Story_Point__c</fullName>
    <inlineHelpText>The level of complexity as estimated in Story Points related to force.com development</inlineHelpText>
    <label>Story Point</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/classes/BurnDownDataProviderSP.cls
/**
 * @author Ashok Kalluri
 * @date 2-Sep-2021
 *
 * @description Controller for Burndown chart by Story Points
 */
public inherited sharing class BurnDownDataProviderSP extends ChartDataProvider {
  public static final String burnDownColor = 'rgba(60, 179, 113, 1);';
  public static final String fullCapacityColor = 'rgba(120, 120, 120, 1);';
  public static final String idealBurnDownColor = 'rgba(255, 99, 71, 1);';
  private String recordId;

  /*******************************************************************************************************
   * @description Not used for this class
   * @param initParameter Object
   */
  public override void init(final Object initParameter) {
    this.recordId = String.valueOf(initParameter);
    // TODO
  }

  /*******************************************************************************************************
   * @description return the data
   * @return List<ChartData> the list of chart data needed to display the graph
   */
  public override List<ChartDataProvider.ChartData> getData() {
    Date todayDate = System.today();
    //Date todayDate = Date.newInstance(2021, 10, 20);
    final List<ChartDataProvider.ChartData> chartDatas = new List<ChartDataProvider.ChartData>();

    List<Double> burnDownDATA = new List<Double>();
    List<Double> fullCapacityDATA = new List<Double>();
    List<Double> idealburnDownDATA = new List<Double>();

    List<String> xAxisData = new List<String>();

    ChartDataProvider.ChartData burnDownChartData = new ChartDataProvider.ChartData();
    ChartDataProvider.ChartData fullCapacityChartData = new ChartDataProvider.ChartData();
    ChartDataProvider.ChartData idealburnDownChartData = new ChartDataProvider.ChartData();

    List<TR_Sprint__c> currentSprint = [
      SELECT TR_Start_Date__c, TR_End_Date__c, TR_Total_Capacity_US_Points__c
      FROM TR_Sprint__c
      WHERE Id = :this.recordId
    ];
    //get all the user stories from the sprint
    List<TR_User_Story__c> userStoriesList = [
      SELECT
        Id,
        Name,
        TR_Allocated_Sprint__c,
        TR_Completed_Date__c,
        TR_Status__c,
        TR_Story_Point__c,
        TR_Allocated_Sprint__r.Name
      FROM TR_User_Story__c
      WHERE TR_Allocated_Sprint__c = :this.recordId
      AND TR_Status__c != 'Cancelled'
      ORDER BY TR_Completed_Date__c ASC NULLS FIRST
    ];

    //calculate total sprint effort
    Double sumOfManDays = 0;
    Double manDaysBeforeSprint = 0;
    Double manDaysAfterSprint = 0;
    for (TR_User_Story__c userStory : userStoriesList) {
      Decimal tempEffort = userStory.TR_Story_Point__c == null
        ? 0
        : Decimal.valueOf(userStory.TR_Story_Point__c);
      sumOfManDays = sumOfManDays + Double.valueOf(tempEffort);
      if (
        currentSprint[0].TR_Start_Date__c == null ||
        currentSprint[0].TR_Start_Date__c > userStory.TR_Completed_Date__c
      ) {
        manDaysBeforeSprint = manDaysBeforeSprint + tempEffort;
      }
      if (
        currentSprint[0].TR_End_Date__c < todayDate &&
        currentSprint[0].TR_End_Date__c < userStory.TR_Completed_Date__c
      ) {
        manDaysAfterSprint = manDaysBeforeSprint + tempEffort;
      }
    }

    //calculate X-axis range
    Integer noSprintDays = currentSprint[0]
      .TR_Start_Date__c.daysBetween(currentSprint[0].TR_End_Date__c);
    for (Integer i = 0; i <= noSprintDays; i++) {
      xAxisData.add(currentSprint[0].TR_Start_Date__c.addDays(i).format());
    }

    //calculate effort remaining for each day
    Double tempIdealBurnDownPerDay =
      sumOfManDays /
      currentSprint[0]
        .TR_Start_Date__c.daysBetween(currentSprint[0].TR_End_Date__c);
    Integer actualSprintCounter = 0;
    for (String dateVal : xAxisData) {
      Date refDateVal = Date.parse(dateVal);
      Double noOfManDaysRemaining = sumOfManDays;
      if (refDateVal <= todayDate) {
        for (TR_User_Story__c userStory : userStoriesList) {
          if (
            userStory.TR_Completed_Date__c != null &&
            userStory.TR_Completed_Date__c <= refDateVal
          ) {
            Decimal tempEffort = userStory.TR_Story_Point__c == null
              ? 0
              : Decimal.valueOf(userStory.TR_Story_Point__c);
            noOfManDaysRemaining =
              noOfManDaysRemaining - Double.valueOf(tempEffort);
          }
        }
        burnDownDATA.add(noOfManDaysRemaining);
      }
      fullCapacityDATA.add(currentSprint[0].TR_Total_Capacity_US_Points__c);
      if (
        refDateVal > currentSprint[0].TR_Start_Date__c &&
        refDateVal <= currentSprint[0].TR_End_Date__c
      ) {
        actualSprintCounter++;
      }
      idealburnDownDATA.add(
        sumOfManDays - (actualSprintCounter * tempIdealBurnDownPerDay)
      );
    }

    if (manDaysBeforeSprint > 0) {
      xAxisData.add(0, 'Before Sprint');
      if (burnDownDATA.isEmpty()) {
        burnDownDATA.add(sumOfManDays - manDaysBeforeSprint);
      } else {
        burnDownDATA.add(0, sumOfManDays - manDaysBeforeSprint);
      }
      fullCapacityDATA.add(0, currentSprint[0].TR_Total_Capacity_US_Points__c);
      idealburnDownDATA.add(0, sumOfManDays);
    }

    if (manDaysAfterSprint > 0 && todayDate > currentSprint[0].TR_End_Date__c) {
      xAxisData.add('After Sprint');
      burnDownDATA.add(0);
      fullCapacityDATA.add(currentSprint[0].TR_Total_Capacity_US_Points__c);
      idealburnDownDATA.add(0);
    }

    //adding the range and data to the chart
    burnDownChartData.labels = xAxisData;
    burnDownChartData.detail = burnDownDATA;
    burnDownChartData.legendtitle = 'Actual Burndown';
    //burnDownChartData.bgColor = burnDownColor;
    chartDatas.add(burnDownChartData);

    fullCapacityChartData.labels = xAxisData;
    fullCapacityChartData.detail = fullCapacityDATA;
    fullCapacityChartData.legendtitle = 'Capacity';
    //fullCapacityChartData.bgColor = fullCapacityColor;
    chartDatas.add(fullCapacityChartData);

    idealburnDownChartData.labels = xAxisData;
    idealburnDownChartData.detail = idealburnDownDATA;
    idealburnDownChartData.legendtitle = 'Ideal Burndown';
    //idealburnDownChartData.bgColor = idealBurnDownColor;
    chartDatas.add(idealburnDownChartData);
    return chartDatas;
  }
}