ProTrackDev/force-app/main/default/objects/TR_Project__c/TR_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Project__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/TR_Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Business_Impact__c.field-meta.xml
<CustomField>
    <fullName>TR_Business_Impact__c</fullName>
    <label>Business Impact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Trivial</fullName>
            </value>
            <value>
                <fullName>1-Low</fullName>
                <isActive>false</isActive>
                <label>1-Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Ext_View_Ticket__c.field-meta.xml
<CustomField>
    <fullName>TR_Ext_View_Ticket__c</fullName>
    <description>Allows the Users to View Tickets (For Experience Cloud Only)</description>
    <formula>$Label.TR_exp_cloud_base_url&amp;&quot;/protrack/s/detail/&quot;&amp;Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>View Ticket (External)</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_My_Tickets_as_Tester__c.field-meta.xml
<CustomField>
    <fullName>TR_My_Tickets_as_Tester__c</fullName>
    <description>To create Salesforce record list view (My Ticket) where Tester = Logged In User</description>
    <formula>IF( TR_Tester__r.TR_User__r.Id  = $User.Id , TRUE, FALSE )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>My Tickets as Tester</label>
    <type>Checkbox</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_NameHyperLink__c.field-meta.xml
<CustomField>
    <fullName>TR_NameHyperLink__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_260, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_260))+&quot;/lightning/r/TR_Ticket__c/&quot;+Id+&quot;/view&quot;, Name, &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Problem__c.field-meta.xml
<CustomField>
    <fullName>TR_Problem__c</fullName>
    <label>Problem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>TR_Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raised</fullName>
                <default>true</default>
                <label>Raised</label>
            </value>
            <value>
                <fullName>In Analysis</fullName>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Ready for Deployment</fullName>
            </value>
            <value>
                <fullName>Ready for Testing</fullName>
            </value>
            <value>
                <fullName>Closed - Complete</fullName>
            </value>
            <value>
                <fullName>Closed - Cannot Replicate</fullName>
            </value>
            <value>
                <fullName>Closed - Consolidated</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
                <isActive>false</isActive>
                <label>Escalated</label>
            </value>
            <value>
                <fullName>In Test</fullName>
                <isActive>false</isActive>
                <label>In Test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Tickets (User Story)</relationshipLabel>
    <relationshipName>Tickets1</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/TR_User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <label>0-Backlog</label>
            </value>
            <value>
                <fullName>Story Definition</fullName>
                <label>1-Story Definition</label>
            </value>
            <value>
                <fullName>Ready for Design</fullName>
                <label>2-Ready for Design</label>
            </value>
            <value>
                <fullName>In Design</fullName>
                <label>3-In Design</label>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
                <label>4-Ready for Development</label>
            </value>
            <value>
                <fullName>In Development</fullName>
                <label>5-In Development</label>
            </value>
            <value>
                <fullName>Ready for Sprint Demo</fullName>
                <label>6-Ready for Sprint Demo</label>
            </value>
            <value>
                <fullName>Ready for Deployment</fullName>
                <label>7-Ready for Deployment</label>
            </value>
            <value>
                <fullName>In Sprint Testing</fullName>
                <label>8-In Sprint Testing</label>
            </value>
            <value>
                <fullName>DONE</fullName>
                <label>9-DONE</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>99-Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/classes/TR_TicketsController.cls
public with sharing class TR_TicketsController {
    public TR_TicketsController() {

    }
    @AuraEnabled(cacheable=true)
    public static List<TR_Ticket__c> getTickets(Integer offsetCount){
        return [
            SELECT TR_NameHyperLink__c, 
            Name, TR_User_Story__c, 
            TR_Project__c, 
            TR_Status__c, 
            TR_Business_Impact__c, 
            TR_Ext_View_Ticket__c, 
            TR_Problem__c from TR_Ticket__c 
            WHERE TR_Status__c = 'Ready for Testing' 
            AND TR_My_Tickets_as_Tester__c = TRUE
            ORDER BY Name
            LIMIT 50 offset:offsetCount
        ];
    }
}