ProTrackDev/force-app/main/default/objects/TR_Project__c/TR_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Project__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Release__c/TR_Release__c.object-meta.xml
<CustomObject>
    <description>This object represents a release or phase for a specific project</description>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Release__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/TR_Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/fields/TR_Release__c.field-meta.xml
<CustomField>
    <fullName>TR_Release__c</fullName>
    <description>Release that is related to the sprint</description>
    <label>Release</label>
    <referenceTo>TR_Release__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Planning</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/TR_User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Acceptance_Criteria__c.field-meta.xml
<CustomField>
    <fullName>TR_Acceptance_Criteria__c</fullName>
    <label>Acceptance Criteria</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Allocated_Release__c.field-meta.xml
<CustomField>
    <fullName>TR_Allocated_Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is automatically populated when you fill in the allocated Sprint</inlineHelpText>
    <label>Allocated Release</label>
    <referenceTo>TR_Release__c</referenceTo>
    <relationshipLabel>Allocated User Stories</relationshipLabel>
    <relationshipName>Allocated_User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Allocated_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Allocated_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Once it has been agreed with the client which sprint will be accommodated for this User Story, use this field to keep this information</inlineHelpText>
    <label>Allocated Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Allocated User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_As_a__c.field-meta.xml
<CustomField>
    <fullName>TR_As_a__c</fullName>
    <inlineHelpText>The main user type(s) this user story is for</inlineHelpText>
    <label>As a</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>TR_Cancellation_Reason__c</fullName>
    <inlineHelpText>The reason this User Story is no longer being considered as valid. This should only be used if the User Story Status has been set to Cancelled</inlineHelpText>
    <label>Cancellation Reason</label>
    <type>TextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Epic_Name__c.field-meta.xml
<CustomField>
    <fullName>TR_Epic_Name__c</fullName>
    <formula>TR_Epic_Ref__r.TR_Epic_Name__c</formula>
    <label>Epic Name</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_External_ID__c.field-meta.xml
<CustomField>
    <fullName>TR_External_ID__c</fullName>
    <description>External ID of the User Story</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_I_want_to__c.field-meta.xml
<CustomField>
    <fullName>TR_I_want_to__c</fullName>
    <inlineHelpText>What the user need to achieve E.g. I want to...be able to search customer on different fields (e.g. first name, address) in my territory</inlineHelpText>
    <label>I want to</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Priority__c.field-meta.xml
<CustomField>
    <fullName>TR_Priority__c</fullName>
    <inlineHelpText>The relative priority of this User Story. 1 is the most important, 99 is the least. This can be used during Sprint Planning</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_So_that__c.field-meta.xml
<CustomField>
    <fullName>TR_So_that__c</fullName>
    <inlineHelpText>Please enter the business value of this User Story. This helps the Developers and Business Analysts understand the important essence of what the user needs to ultimately achieve.</inlineHelpText>
    <label>So that</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <label>0-Backlog</label>
            </value>
            <value>
                <fullName>Story Definition</fullName>
                <label>1-Story Definition</label>
            </value>
            <value>
                <fullName>Ready for Design</fullName>
                <label>2-Ready for Design</label>
            </value>
            <value>
                <fullName>In Design</fullName>
                <label>3-In Design</label>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
                <label>4-Ready for Development</label>
            </value>
            <value>
                <fullName>In Development</fullName>
                <label>5-In Development</label>
            </value>
            <value>
                <fullName>Ready for Sprint Demo</fullName>
                <label>6-Ready for Sprint Demo</label>
            </value>
            <value>
                <fullName>Ready for Deployment</fullName>
                <label>7-Ready for Deployment</label>
            </value>
            <value>
                <fullName>In Sprint Testing</fullName>
                <label>8-In Sprint Testing</label>
            </value>
            <value>
                <fullName>DONE</fullName>
                <label>9-DONE</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>99-Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Story_Title__c.field-meta.xml
<CustomField>
    <fullName>TR_Story_Title__c</fullName>
    <label>Story Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/classes/GeneratePdfFunctionalController.cls
public class GeneratePdfFunctionalController {
  public List<EpicStoryWrapper> epicStoryWrapperList { get; set; }

  public GeneratePdfFunctionalController(
    ApexPages.StandardController stdController
  ) {
    TR_Release__c releaseRecord = (TR_Release__c) stdController.getRecord();
    Map<String, List<TR_User_Story__c>> epicStoryMap = new Map<String, List<TR_User_Story__c>>();
    //find all user stories'
    for (TR_User_Story__c userStory : [
      SELECT
        Id,
        Name,
        TR_Allocated_Sprint__r.Name,
        TR_As_a__c,
        TR_I_want_to__c,
        TR_So_that__c,
        TR_Story_Title__c,
        TR_Project__r.Name,
        TR_Epic_Name__c,
        TR_Status__c,
        TR_Priority__c,
        TR_Approval_Status__c,
        TR_Cancellation_Reason__c,
        TR_External_ID__c,
        TR_Acceptance_Criteria__c,
        TR_Allocated_Release__r.Name
      FROM TR_User_Story__c
      WHERE TR_Allocated_Release__c = :releaseRecord.Id
      ORDER BY TR_Epic_Name__c, Id NULLS FIRST
    ]) {
      List<TR_User_Story__c> tmpMap = new List<TR_User_Story__c>();
      if (epicStoryMap.containsKey(userStory.TR_Epic_Name__c)) {
        tmpMap = epicStoryMap.get(userStory.TR_Epic_Name__c);
      }
      tmpMap.add(userStory);
      epicStoryMap.put(userStory.TR_Epic_Name__c, tmpMap);
    }

    epicStoryWrapperList = new List<EpicStoryWrapper>();
    for (String epicName : epicStoryMap.keySet()) {
      epicStoryWrapperList.add(
        new EpicStoryWrapper(epicName, epicStoryMap.get(epicName))
      );
    }
  }

  public class EpicStoryWrapper {
    public String epicName { get; set; }
    public List<TR_User_Story__c> userStories { get; set; }
    public EpicStoryWrapper(
      String epicName,
      List<TR_User_Story__c> userStories
    ) {
      this.epicName = epicName;
      this.userStories = userStories;
    }
  }
}