ProTrackDev/force-app/main/default/objects/TR_Project__c/TR_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Project__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/TR_Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Planning</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/TR_Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Started</fullName>
                <color>#78C953</color>
                <label>Started</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <color>#0B6FCE</color>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Awaiting Retest</fullName>
                <color>#A845DC</color>
                <label>Awaiting Retest</label>
            </value>
            <value>
                <fullName>Parked</fullName>
                <color>#F3D904</color>
                <label>Parked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Template__c.field-meta.xml
<CustomField>
    <fullName>TR_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/TR_Test_Execution_Step__c.object-meta.xml
<CustomObject>
    <label>Test Execution Step</label>
    <nameField>
        <displayFormat>TES-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Action__c.field-meta.xml
<CustomField>
    <fullName>TR_Action__c</fullName>
    <label>Action</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Comments__c.field-meta.xml
<CustomField>
    <fullName>TR_Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Sequence__c.field-meta.xml
<CustomField>
    <fullName>TR_Sequence__c</fullName>
    <formula>IF(LEN(TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c)) &lt;2, &quot;0&quot; &amp; TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c ), TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sequence</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Step_Outcome__c.field-meta.xml
<CustomField>
    <fullName>TR_Step_Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
                <color>#0B6FCE</color>
                <label>Pass</label>
            </value>
            <value>
                <fullName>Passed with issues</fullName>
                <color>#F3D904</color>
                <label>Passed with issues</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <color>#FF0000</color>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Execution__c</fullName>
    <label>Test Execution</label>
    <referenceTo>TR_Test_Execution__c</referenceTo>
    <relationshipLabel>Test Execution Steps</relationshipLabel>
    <relationshipName>Test_Execution_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Tester_Role__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester_Role__c</fullName>
    <label>Tester Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Tips__c.field-meta.xml
<CustomField>
    <fullName>TR_Tips__c</fullName>
    <label>Tips</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/TR_Test_Script__c.object-meta.xml
<CustomObject>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Tester_Role__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester_Role__c</fullName>
    <label>Tester Role</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/TR_Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>TR_Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Execution</label>
    <referenceTo>TR_Test_Execution__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Script__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Tickets (User Story)</relationshipLabel>
    <relationshipName>Tickets1</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/TR_User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/globalValueSets/TR_Test_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sprint Testing</fullName>
    </customValue>
    <customValue>
        <fullName>SIT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>UAT</fullName>
    </customValue>
    <masterLabel>Test Phase</masterLabel>
</GlobalValueSet>

ProTrackDev/force-app/main/default/classes/TR_RunTestExecution_Controller.cls
public with sharing class TR_RunTestExecution_Controller {
    
    @AuraEnabled
    public static TR_Test_Execution__c retrieveTestExecutionData(Id testExecutionId) {
        TR_Test_Execution__c testExecution = [
            SELECT Id, Name,TR_Project__c, TR_Sprint__c, TR_Template__c, TR_User_Story__c, TR_Test_Phase__c
            FROM TR_Test_Execution__c WHERE Id =: testExecutionId LIMIT 1
        ];
       
        return testExecution;
        
    }

    @AuraEnabled
    public static List<Id> retrieveTestStepsIds(Id testExecutionId) {
        Map<Id, TR_Test_Execution_Step__c> stepMap = retrieveTestStepsMap(testExecutionId);
        List<Id> stepIdList = new List<Id>(stepMap.keyset());

        return stepIdList;
    }
    @AuraEnabled
    public static Map<ID, TR_Test_Execution_Step__c> retrieveTestStepsMap(Id testExecutionId) {
        Map<Id, TR_Test_Execution_Step__c> stepMap = new Map<Id, TR_Test_Execution_Step__c>();
        
        for(TR_Test_Execution_Step__c testStep:[
            SELECT TR_Sequence__c,Name,TR_Action__c,TR_Expected_Result__c, TR_Step_Outcome__c,TR_Comments__c,TR_Tips__c,Id,TR_Tester_Role__c
            FROM TR_Test_Execution_Step__c 
            WHERE TR_Test_Execution__c =: testExecutionId
            ORDER BY TR_Sequence__c ASC]){

            stepMap.put(testStep.id,testStep);
            
        }

        
        return stepMap;
        
    }
    @AuraEnabled
    public static List<Id> retrieveTestTicketIds(Id testScriptId) {
        Map<Id, TR_Ticket__c> ticketMap = retrieveTestTicketsMapbyTestScript(testScriptId);
        List<Id> ticketIdList = new List<Id>(ticketMap.keyset());
        return ticketIdList;
        
    }
    @AuraEnabled
    public static List<Id> retrieveTestTicketIdsbyExecution(Id testExecutionId) {
        Map<Id, TR_Ticket__c> ticketMap = retrieveTestTicketsMapbyExecution(testExecutionId);
        List<Id> ticketIdList = new List<Id>(ticketMap.keyset());
        return ticketIdList;
        
    }
    @AuraEnabled
    public static Map<ID, TR_Ticket__c> retrieveTestTicketsMapbyTestScript(Id testScriptId) {
        Map<Id, TR_Ticket__c> stepMap = new Map<Id, TR_Ticket__c>();
        
        for(TR_Ticket__c testTicket:[
            SELECT Id, Name
            FROM TR_Ticket__c 
            WHERE TR_Test_Script__c =: testScriptId]){

            stepMap.put(testTicket.id,testTicket); 
        }
        return stepMap;
    }
    @AuraEnabled
    public static Map<ID, TR_Ticket__c> retrieveTestTicketsMapbyExecution(Id testExecutionId) {
        Map<Id, TR_Ticket__c> ticketMap = new Map<Id, TR_Ticket__c>();
        
        for(TR_Ticket__c testTicket:[
            SELECT Id, Name
            FROM TR_Ticket__c 
            WHERE TR_Test_Execution__c =: testExecutionId]){

            ticketMap.put(testTicket.id,testTicket); 
        }

        return ticketMap;
    }
    @AuraEnabled
    public static String retrieverelatedTestScriptIds(Id testExecutionId) {
        Id templateId = [
            SELECT TR_Template__c 
            FROM TR_Test_Execution__c 
            WHERE Id =: testExecutionId 
        ].TR_Template__c;
       
        return templateId;
        
    }

    @AuraEnabled
    public static void updateTestExecutionStatustoStarted(Id testExecutionStepId) {
        system.System.debug('testExecutionStepId');
        system.System.debug(testExecutionStepId);
        Id execId = [SELECT TR_Test_Execution__c FROM TR_Test_Execution_Step__c WHERE Id =: testExecutionStepId].TR_Test_Execution__c;
        
        system.System.debug('execId');
        system.System.debug(execId);

        TR_Test_Execution__c testExec= new TR_Test_Execution__c();

        testExec = [SELECT Id, TR_Status__c FROM TR_Test_Execution__c WHERE Id =: execId LIMIT 1];
        
        if(testExec.TR_Status__c != 'Started'){
            testExec.TR_Status__c = 'Started';
        }

        update testExec;
        
    }
}