ProTrackDev/force-app/main/default/objects/TR_Project__c/TR_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Project__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/TR_Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Started</fullName>
                <color>#78C953</color>
                <label>Started</label>
            </value>
            <value>
                <fullName>Complete</fullName>
                <color>#0B6FCE</color>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Awaiting Retest</fullName>
                <color>#A845DC</color>
                <label>Awaiting Retest</label>
            </value>
            <value>
                <fullName>Parked</fullName>
                <color>#F3D904</color>
                <label>Parked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/TR_Test_Execution_Step__c.object-meta.xml
<CustomObject>
    <label>Test Execution Step</label>
    <nameField>
        <displayFormat>TES-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Action__c.field-meta.xml
<CustomField>
    <fullName>TR_Action__c</fullName>
    <label>Action</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Comments__c.field-meta.xml
<CustomField>
    <fullName>TR_Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Sequence__c.field-meta.xml
<CustomField>
    <fullName>TR_Sequence__c</fullName>
    <formula>IF(LEN(TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c)) &lt;2, &quot;0&quot; &amp; TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c ), TEXT(TR_Template_Step__r.TR_Ranked_Sequence__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sequence</label>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Step_Outcome__c.field-meta.xml
<CustomField>
    <fullName>TR_Step_Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pass</fullName>
                <color>#0B6FCE</color>
                <label>Pass</label>
            </value>
            <value>
                <fullName>Passed with issues</fullName>
                <color>#F3D904</color>
                <label>Passed with issues</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <color>#FF0000</color>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Execution__c</fullName>
    <label>Test Execution</label>
    <referenceTo>TR_Test_Execution__c</referenceTo>
    <relationshipLabel>Test Execution Steps</relationshipLabel>
    <relationshipName>Test_Execution_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Tips__c.field-meta.xml
<CustomField>
    <fullName>TR_Tips__c</fullName>
    <label>Tips</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/TR_Test_Script__c.object-meta.xml
<CustomObject>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/TR_Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Business_Impact__c.field-meta.xml
<CustomField>
    <fullName>TR_Business_Impact__c</fullName>
    <label>Business Impact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Minor</fullName>
            </value>
            <value>
                <fullName>Trivial</fullName>
            </value>
            <value>
                <fullName>1-Low</fullName>
                <isActive>false</isActive>
                <label>1-Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Functional_Comment__c.field-meta.xml
<CustomField>
    <fullName>TR_Functional_Comment__c</fullName>
    <inlineHelpText>Fill in here all the additional comments, screenshots or steps to reproduce the issue</inlineHelpText>
    <label>Comments / Notes / Steps</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Problem__c.field-meta.xml
<CustomField>
    <fullName>TR_Problem__c</fullName>
    <label>Problem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Problem_Description__c.field-meta.xml
<CustomField>
    <fullName>TR_Problem_Description__c</fullName>
    <label>Problem Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raised</fullName>
                <default>true</default>
                <label>Raised</label>
            </value>
            <value>
                <fullName>In Analysis</fullName>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Ready for Deployment</fullName>
            </value>
            <value>
                <fullName>Ready for Testing</fullName>
            </value>
            <value>
                <fullName>Closed - Complete</fullName>
            </value>
            <value>
                <fullName>Closed - Cannot Replicate</fullName>
            </value>
            <value>
                <fullName>Closed - Consolidated</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
                <isActive>false</isActive>
                <label>Escalated</label>
            </value>
            <value>
                <fullName>In Test</fullName>
                <isActive>false</isActive>
                <label>In Test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Execution</label>
    <referenceTo>TR_Test_Execution__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Test_Script__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Ticket__c/fields/TR_Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>TR_Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
            <value>
                <fullName>Inquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/TR_User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Status__c.field-meta.xml
<CustomField>
    <fullName>TR_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <label>0-Backlog</label>
            </value>
            <value>
                <fullName>Story Definition</fullName>
                <label>1-Story Definition</label>
            </value>
            <value>
                <fullName>Ready for Design</fullName>
                <label>2-Ready for Design</label>
            </value>
            <value>
                <fullName>In Design</fullName>
                <label>3-In Design</label>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
                <label>4-Ready for Development</label>
            </value>
            <value>
                <fullName>In Development</fullName>
                <label>5-In Development</label>
            </value>
            <value>
                <fullName>Ready for Sprint Demo</fullName>
                <label>6-Ready for Sprint Demo</label>
            </value>
            <value>
                <fullName>Ready for Deployment</fullName>
                <label>7-Ready for Deployment</label>
            </value>
            <value>
                <fullName>In Sprint Testing</fullName>
                <label>8-In Sprint Testing</label>
            </value>
            <value>
                <fullName>DONE</fullName>
                <label>9-DONE</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>99-Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/classes/TR_LWC_DataLayer.cls
public with sharing class TR_LWC_DataLayer {
  @AuraEnabled(cacheable=true)
  public static List<TR_Test_Execution_Step__c> getTRTestExecutionStepByTestExecutionId(
    Id TestExecutionId
  ) {
    System.debug('TheOTestExecutionIdfficeIs:' + TestExecutionId);
    return [
      SELECT
        Id,
        Name,
        TR_Sequence__c,
        TR_Action__c,
        TR_Expected_Result__c,
        TR_Tips__c,
        TR_Step_Outcome__c,
        TR_Comments__c
      FROM TR_Test_Execution_Step__c
      WHERE TR_Test_Execution__c = :TestExecutionId
      ORDER BY TR_Sequence__c ASC
    ];
  }

  @AuraEnabled
  public static string updateTestExecutionSteps(Object data) {
    List<TR_Test_Execution_Step__c> testExecutionStepsToUpdate = (List<TR_Test_Execution_Step__c>) JSON.deserialize(
         JSON.serialize(data),
         List<TR_Test_Execution_Step__c>.class
    );
    try {
        update testExecutionStepsToUpdate;
        return 'Success: records updated successfully';
    }
    catch (Exception e) {
        return 'The following exception has occurred: ' + e.getMessage();
    }}

  @AuraEnabled(cacheable=true)
  public static List<TR_Ticket__c> getTicketsByTestExecutionId(
    Id TestExecutionId
  ) {
    return [
      SELECT
        Id,
        Name,
        TR_Problem__c,
        TR_Problem_Description__c,
        TR_Status__c,
        TR_Business_Impact__c,
        CreatedDate
      FROM TR_Ticket__c
      WHERE TR_Test_Execution__c = :TestExecutionId
      ORDER BY CreatedDate DESC
    ];
  }

  @AuraEnabled
  public static void createTicket(
    String problem,
    String problemDescription,
    String comments,
    String businessImpact,
    String ticketType,
    String status,
    String testScript,
    String project,
    String loggedBy,
    String testExecution,
    String testPhase,
    String userStory,
    String tester
  ) {
    TR_Ticket__c ticket = new TR_Ticket__c();
    ticket.TR_Problem__c = problem;
    ticket.TR_Problem_Description__c = problemDescription;
    ticket.TR_Functional_Comment__c = comments; 
    ticket.TR_Business_Impact__c = businessImpact;
    ticket.TR_Ticket_Type__c = ticketType;
    ticket.TR_Status__c = status;
    ticket.TR_Test_Script__c = testScript;
    ticket.TR_Project__c = project;
    ticket.TR_Logged_by__c = loggedBy;
    ticket.TR_Test_Execution__c = testExecution;
    ticket.TR_Test_Phase__c = testPhase;
    ticket.TR_User_Story__c = userStory;
    ticket.TR_Tester__c = tester;
    try{
        insert ticket;
    } catch (Exception ex){
        throw new AuraHandledException(ex.getMessage());
    }
  }
}