ProTrackDev/force-app/main/default/objects/TR_Project__c/TR_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Sprint__c/TR_Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/TR_Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Execution Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Template__c.field-meta.xml
<CustomField>
    <fullName>TR_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Tester__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_Tester_Relationship__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tester Relationship</label>
    <referenceTo>TR_Tester__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Test Execution</relationshipLabel>
    <relationshipName>Test_Execution</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/TR_Test_Execution_Step__c.object-meta.xml
<CustomObject>
    <label>Test Execution Step</label>
    <nameField>
        <displayFormat>TES-{000000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Execution Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Action__c.field-meta.xml
<CustomField>
    <fullName>TR_Action__c</fullName>
    <label>Action</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Template_Step__c.field-meta.xml
<CustomField>
    <fullName>TR_Template_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template Step</label>
    <referenceTo>TR_Test_Script_Step__c</referenceTo>
    <relationshipLabel>Test Execution Steps</relationshipLabel>
    <relationshipName>Test_Execution_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Execution__c</fullName>
    <label>Test Execution</label>
    <referenceTo>TR_Test_Execution__c</referenceTo>
    <relationshipLabel>Test Execution Steps</relationshipLabel>
    <relationshipName>Test_Execution_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Execution_Step__c/fields/TR_Tester_Role__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester_Role__c</fullName>
    <label>Tester Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/TR_Test_Script__c.object-meta.xml
<CustomObject>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Test Script Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_Tester_Role__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester_Role__c</fullName>
    <label>Tester Role</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script__c/fields/TR_User_Story__c.field-meta.xml
<CustomField>
    <fullName>TR_User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>TR_User_Story__c</referenceTo>
    <relationshipLabel>Test Scripts</relationshipLabel>
    <relationshipName>Test_Scripts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/TR_Test_Script_Step__c.object-meta.xml
<CustomObject>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>TSS-{000000}</displayFormat>
        <label>Test Script Step Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Action__c.field-meta.xml
<CustomField>
    <fullName>TR_Action__c</fullName>
    <label>Action</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Action_Long__c.field-meta.xml
<CustomField>
    <fullName>TR_Action_Long__c</fullName>
    <label>Action Long</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>TR_Expected_Result__c</fullName>
    <label>Expected Result</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Ranked_Sequence__c.field-meta.xml
<CustomField>
    <fullName>TR_Ranked_Sequence__c</fullName>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Sequence_Last_Updated_By__c.field-meta.xml
<CustomField>
    <fullName>TR_Sequence_Last_Updated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sequence Last Updated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Script_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Test_Script__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Script</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Test Script Steps</relationshipLabel>
    <relationshipName>Test_Script_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Test_Script_Step__c/fields/TR_Tester_Role__c.field-meta.xml
<CustomField>
    <fullName>TR_Tester_Role__c</fullName>
    <label>Tester Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Tester__c/TR_Tester__c.object-meta.xml
<CustomObject>
    <label>Tester</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tester Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Testers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_Tester__c/fields/TR_Test_Phase__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Phase__c</fullName>
    <label>Test Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TR_Test_Phase</valueSetName>
    </valueSet>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Tester__c/fields/TR_Test_Template__c.field-meta.xml
<CustomField>
    <fullName>TR_Test_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Template</label>
    <referenceTo>TR_Test_Script__c</referenceTo>
    <relationshipLabel>Test Script Testers</relationshipLabel>
    <relationshipName>Testers</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_Tester__c/fields/TR_User__c.field-meta.xml
<CustomField>
    <fullName>TR_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Testers</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/TR_User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Allocated_Sprint__c.field-meta.xml
<CustomField>
    <fullName>TR_Allocated_Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Once it has been agreed with the client which sprint will be accommodated for this User Story, use this field to keep this information</inlineHelpText>
    <label>Allocated Sprint</label>
    <referenceTo>TR_Sprint__c</referenceTo>
    <relationshipLabel>Allocated User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

ProTrackDev/force-app/main/default/objects/TR_User_Story__c/fields/TR_Project__c.field-meta.xml
<CustomField>
    <fullName>TR_Project__c</fullName>
    <inlineHelpText>The Project responsible for delivering this User Story</inlineHelpText>
    <label>Project</label>
    <referenceTo>TR_Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProTrackDev/force-app/main/default/globalValueSets/TR_Test_Phase.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sprint Testing</fullName>
    </customValue>
    <customValue>
        <fullName>SIT</fullName>
    </customValue>
    <customValue>
        <fullName>SAT</fullName>
    </customValue>
    <customValue>
        <fullName>UAT</fullName>
    </customValue>
    <masterLabel>Test Phase</masterLabel>
</GlobalValueSet>

ProTrackDev/force-app/main/default/classes/TR_Tester_TriggerClass.cls
/***************************************************************************************************************************
 * Name:        FXA_Tester_TriggerClass
 * Description: The class used by the trigger FXA_Tester_Trigger 
 *              on TR_Tester__c to handle logical operations 
 *              for dml operations
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 12/07/2017       Josephine Del Mundo             Created   
 ****************************************************************************************************************************/
public without sharing class TR_Tester_TriggerClass {  
    /*  Description: creates TR_Test_Execution__c and TR_Test_Execution_Step__c records
     *  Author: Del Mundo, Josephine
     *  Date Created: 12-JUL-2017
     *  Input Parameters: list<TR_Tester__c> 
     *  Return: none
     */    
    public static void routineAfterInsert(list<TR_Tester__c> trigger_new) {
        List<TR_Test_Execution__c> execList = new List<TR_Test_Execution__c>();
        List<TR_Test_Execution_Step__c> stepcList = new List<TR_Test_Execution_Step__c>();
        Set<Id> scriptIds = new Set<Id>();
        
        for(TR_Tester__c rec : trigger_new){
            scriptIds.add(rec.TR_Test_Template__c);
        }
        
        Map<Id, TR_Test_Script__c> scriptMap = new Map<Id,TR_Test_Script__c>([SELECT TR_Project__c,TR_User_Story__c
                                                        FROM TR_Test_Script__c WHERE Id IN :scriptIds]);
                                                        
        Map<Id, TR_User_Story__c> userMap = new Map<Id, TR_User_Story__c>(); 
        if(!scriptMap.isEmpty()){
            Set<Id> userStoryIds = new Set<Id>();
            for(TR_Test_Script__c rec :  scriptMap.values()){
                if(rec.TR_User_Story__c != null) userStoryIds.add(rec.TR_User_Story__c);
            }
            
            Map<Id, TR_User_Story__c> userStorySprintId = new Map<Id, TR_User_Story__c>([SELECT TR_Allocated_Sprint__c 
                                                             FROM TR_User_Story__c
                                                             WHERE Id IN: userStoryIds]);
                                                             
            List<TR_Test_Script_Step__c> testScriptList = new List<TR_Test_Script_Step__c>([SELECT Name,TR_Action_Long__c,
                                                                TR_Action__c,TR_Expected_Result__c,TR_Ranked_Sequence__c,
                                                                TR_Sequence_Last_Updated_By__c,TR_Test_Script__c,
                                                                TR_Tester_Role__c
                                                                FROM TR_Test_Script_Step__c
                                                                WHERE TR_Test_Script__c IN:scriptIds]);
            for(TR_Tester__c rec : trigger_new){
                if(!scriptMap.isEmpty() && scriptMap.containsKey(rec.TR_Test_Template__c)){
                execList.add(new TR_Test_Execution__c(TR_Template__c = rec.TR_Test_Template__c,
                            TR_User_Story__c = (scriptMap.get(rec.TR_Test_Template__c).TR_User_Story__c),
                            TR_Project__c = (scriptMap.get(rec.TR_Test_Template__c).TR_Project__c),
                            TR_Tester__c = rec.TR_User__c,
                            TR_Test_Phase__c = rec.TR_Test_Phase__c,
                            TR_Tester_Relationship__c = rec.Id,
                            TR_Sprint__c = (userStorySprintId.containsKey(scriptMap.get(rec.TR_Test_Template__c).TR_User_Story__c) 
                                            ? userStorySprintId.get(scriptMap.get(rec.TR_Test_Template__c).TR_User_Story__c).TR_Allocated_Sprint__c 
                                            : null)));
                }
            }
            
            if(!execList.isEmpty()){
                insert execList;
                
                for(integer i = 0; i< execList.size(); i++){
                    for(TR_Test_Script_Step__c rec : testScriptList){
                        stepcList.add(new TR_Test_Execution_Step__c(TR_Test_Execution__c = execList[i].Id,
                                                                    TR_Template_Step__c = rec.Id,
                                                                    TR_Expected_Result__c = rec.TR_Expected_Result__c,
                                                                    TR_Action__c = rec.TR_Action__c,
                                                                    TR_Tester_Role__c = rec.TR_Tester_Role__c));    
                    }
                }
                if(!stepcList.isEmpty()){
                    insert stepcList;
                }
                
            }
        }
    }//end of routineAfterInsert
    
    
}